### ISSUE TITLE
Build error on Node 0.12 & Darwin

### ISSUE THREAD

**Issue by thom-nic** [shovon/sync-prompt#15]
```
> sync-prompt@0.2.2 install /Users/thom/dev/voltserver/auto-tester-ui/node_modules/locus/node_modules/sync-prompt
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@0.12.2 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/thom/dev/voltserver/auto-tester-ui/node_modules/locus/node_modules/sync-prompt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/thom/.node-gyp/0.12.2/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/thom/.node-gyp/0.12.2',
gyp info spawn args   '-Dmodule_root_dir=/Users/thom/dev/voltserver/auto-tester-ui/node_modules/locus/node_modules/sync-prompt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/sync_prompt/src/sync_prompt.o
../src/sync_prompt.cc:33:18: error: variable has incomplete type 'struct termios'
  struct termios tty;
                 ^
../src/sync_prompt.cc:33:10: note: forward declaration of 'termios'
  struct termios tty;
         ^
../src/sync_prompt.cc:36:21: error: use of undeclared identifier 'ECHO'
    tty.c_lflag &= ~ECHO;
                    ^
../src/sync_prompt.cc:38:20: error: use of undeclared identifier 'ECHO'
    tty.c_lflag |= ECHO;
                   ^
../src/sync_prompt.cc:40:34: error: use of undeclared identifier 'TCSANOW'
  (void) tcsetattr(STDIN_FILENO, TCSANOW, &tty);
                                 ^
../src/sync_prompt.cc:50:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> HiddenPrompt(const Arguments& args) {
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/thom/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/sync_prompt.cc:51:15: error: calling a protected constructor of class 'v8::HandleScope'
  HandleScope scope;
              ^
/Users/thom/.node-gyp/0.12.2/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/sync_prompt.cc:55:16: error: no member named 'Close' in 'v8::HandleScope'
  return scope.Close(String::New(retval.c_str()));
         ~~~~~ ^
../src/sync_prompt.cc:55:30: error: no member named 'New' in 'v8::String'
  return scope.Close(String::New(retval.c_str()));
                     ~~~~~~~~^
../src/sync_prompt.cc:58:28: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> Prompt(const Arguments& args) {
                           ^~~~~~~~~
                           v8::internal::Arguments
/Users/thom/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/sync_prompt.cc:59:15: error: calling a protected constructor of class 'v8::HandleScope'
  HandleScope scope;
              ^
/Users/thom/.node-gyp/0.12.2/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/sync_prompt.cc:61:16: error: no member named 'Close' in 'v8::HandleScope'
  return scope.Close(String::New(retval.c_str()));
         ~~~~~ ^
../src/sync_prompt.cc:61:30: error: no member named 'New' in 'v8::String'
  return scope.Close(String::New(retval.c_str()));
                     ~~~~~~~~^
../src/sync_prompt.cc:65:24: error: no member named 'NewSymbol' in 'v8::String'
  exports->Set(String::NewSymbol("prompt"),
               ~~~~~~~~^
../src/sync_prompt.cc:66:27: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of
      type 'Handle<v8::Value> (const v8::internal::Arguments &)'
    FunctionTemplate::New(Prompt)->GetFunction());
                          ^~~~~~
/Users/thom/.node-gyp/0.12.2/deps/v8/include/v8.h:3456:16: note: passing argument to parameter 'isolate'
      here
      Isolate* isolate,
               ^
../src/sync_prompt.cc:67:24: error: no member named 'NewSymbol' in 'v8::String'
  exports->Set(String::NewSymbol("hiddenPrompt"),
               ~~~~~~~~^
../src/sync_prompt.cc:68:27: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of
      type 'Handle<v8::Value> (const v8::internal::Arguments &)'
    FunctionTemplate::New(HiddenPrompt)->GetFunction());
                          ^~~~~~~~~~~~
/Users/thom/.node-gyp/0.12.2/deps/v8/include/v8.h:3456:16: note: passing argument to parameter 'isolate'
      here.
      Isolate* isolate,
               ^
16 errors generated.
make: *** [Release/obj.target/sync_prompt/src/sync_prompt.o] Error 1
```

Unsure if this is related to #11.  I also see pretty much the same error if I try to build against iojs 1.8.1.

**Comment by DanielAron** [comment]
Same error here.
This is  my npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/daniel/.nvm/v0.12.2/bin/node',
1 verbose cli   '/Users/daniel/.nvm/v0.12.2/bin/npm',
1 verbose cli   'install',
1 verbose cli   'sync-prompt' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 warn package.json CreateFonkApp@1.0.0 No repository field.
5 silly cache add args [ 'sync-prompt', null ]
6 verbose cache add spec sync-prompt
7 silly cache add parsed spec { raw: 'sync-prompt',
7 silly cache add   scope: null,
7 silly cache add   name: 'sync-prompt',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed sync-prompt@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'sync-prompt', range: '*', hasData: false }
12 silly mapToRegistry name sync-prompt
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/sync-prompt
16 verbose addNameRange registry:https://registry.npmjs.org/sync-prompt not in flight; fetching
17 verbose request uri https://registry.npmjs.org/sync-prompt
18 verbose request no auth needed
19 info attempt registry request try #1 at 3:16:38 PM
20 verbose request id
21 verbose etag
22 http request GET https://registry.npmjs.org/sync-prompt
23 http 304 https://registry.npmjs.org/sync-prompt
24 silly get cb [ 304,
24 silly get   { date: 'Thu, 04 Jun 2015 18:04:29 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag:
24 silly get     age: '0',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-iad2140-IAD',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '1',
24 silly get     'x-timer': 
24 silly get     vary: 'Accept' } ]
25 verbose etag https://registry.npmjs.org/sync-prompt from cache
26 verbose get saving sync-prompt to /Users/daniel/.npm/registry.npmjs.org/sync-prompt/.cache.json
27 silly addNameRange number 2 { name: 'sync-prompt', range: '*', hasData: true }
28 silly addNameRange versions [ 'sync-prompt',
28 silly addNameRange   [ '0.0.0',
28 silly addNameRange     '0.0.1',
28 silly addNameRange     '0.1.0',
28 silly addNameRange     '0.2.0',
28 silly addNameRange     '0.2.1',
28 silly addNameRange     '0.2.2',
28 silly addNameRange     '0.3.1',
28 silly addNameRange     '0.3.2',
28 silly addNameRange     '0.3.3-beta',
28 silly addNameRange     '0.4.0',
28 silly addNameRange     '0.4.1',
28 silly addNameRange     '0.4.2' ] ]
29 verbose addNamed sync-prompt@0.4.2
30 silly addNamed semver.valid 0.4.2
31 silly addNamed semver.validRange 0.4.2
32 silly cache afterAdd sync-prompt@0.4.2
33 verbose afterAdd /Users/daniel/.npm/sync-prompt/0.4.2/package/package.json not in flight; writing
34 verbose afterAdd /Users/daniel/.npm/sync-prompt/0.4.2/package/package.json written
35 silly install resolved [ { name: 'sync-prompt',
35 silly install resolved     description: 'The missing prompt function for Node.js',
35 silly install resolved     homepage: 'https://github.com/shovon/sync-prompt',
35 silly install resolved     keywords:
35 silly install resolved      [ 'command',
35 silly install resolved        'line',
35 silly install resolved        'io',
35 silly install resolved        'cli',
35 silly install resolved        'commandline',
35 silly install resolved        'commandlineinterface',
35 silly install resolved        'commandlineinput',
35 silly install resolved        'input',
35 silly install resolved        'output',
35 silly install resolved        'stdin',
35 silly install resolved        'synchronous' ],
35 silly install resolved     version: '0.4.2',
35 silly install resolved     author:
35 silly install resolved      { name: 'Salehen Shovon Rahman',
35 silly install resolved        email: 'sal@linux.com',
35 silly install resolved        url: 'http://shovon.github.io' },
35 silly install resolved     scripts:
35 silly install resolved      { test: './node_modules/mocha/bin/mocha && ./node_modules/jshint/bin/jshint .',
35 silly install resolved        coverage: './node_modules/istanbul/lib/cli.js cover _mocha -- -u exports -R spec',
35 silly install resolved        coveralls: './node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage',
35 silly install resolved        install: 'node-gyp rebuild' },
35 silly install resolved     repository:
35 silly install resolved      { type: 'git',
35 silly install resolved        url: 'https://github.com/shovon/sync-prompt.git' },
35 silly install resolved     bugs: { url: 'https://github.com/shovon/sync-prompt/issues' },
35 silly install resolved     license:
35 silly install resolved      { type: 'MIT',
35 silly install resolved        url: 'https://github.com/shovon/blob/master/LICENSE' },
35 silly install resolved     main: './lib/sync-prompt',
35 silly install resolved     devDependencies:
35 silly install resolved      { sinon: '~1.7.3',
35 silly install resolved        jshint: '~2.1.4',
35 silly install resolved        mocha: '~1.12.0',
35 silly install resolved        istanbul: '~0.1.44',
35 silly install resolved        coveralls: '~2.3.0',
35 silly install resolved        'mocha-lcov-reporter': '0.0.1' },
35 silly install resolved     gypfile: true,
35 silly install resolved     gitHead: '088a39c65c5efc4cef94717ea6ff6ad7869fc17e',
35 silly install resolved     _id: 'sync-prompt@0.4.2',
35 silly install resolved     _shasum: '9bf28c298dbd362189713087c277b4e903aaf371',
35 silly install resolved     _from: 'sync-prompt@*',
35 silly install resolved     _npmVersion: '2.5.1',
35 silly install resolved     _nodeVersion: '1.2.0',
35 silly install resolved     _npmUser: { name: 'shovon', email: 'sal@linux.com' },
35 silly install resolved     maintainers: [ [Object] ],
35 silly install resolved     dist:
35 silly install resolved      { shasum: '9bf28c298dbd362189713087c277b4e903aaf371',
35 silly install resolved        tarball: 'http://registry.npmjs.org/sync-prompt/-/sync-prompt-0.4.2.tgz' },
35 silly install resolved     directories: {},
35 silly install resolved     _resolved: 'https://registry.npmjs.org/sync-prompt/-/sync-prompt-0.4.2.tgz',
35 silly install resolved     readme: 'ERROR: No README data found!' } ]
36 info install sync-prompt@0.4.2 into /Users/daniel/workspace/fonco/createProjectFromTerminal
37 info installOne sync-prompt@0.4.2
38 verbose installOne of sync-prompt to /Users/daniel/workspace/fonco/createProjectFromTerminal not in flight; installing
39 verbose lock using /Users/daniel/.npm/_locks/sync-prompt-0f417bb4b3218d70.lock for /Users/daniel/workspace/fonco/createProjectFromTerminal/node_modules/sync-prompt
40 silly install write writing sync-prompt 0.4.2 to /Users/daniel/workspace/fonco/createProjectFromTerminal/node_modules/sync-prompt
41 silly cache addNamed cb sync-prompt@0.4.2
42 verbose unbuild node_modules/sync-prompt
43 silly gentlyRm /Users/daniel/workspace/fonco/createProjectFromTerminal/node_modules/sync-prompt is being purged from base /Users/daniel/workspace/fonco/createProjectFromTerminal
44 verbose gentlyRm don't care about contents; nuking /Users/daniel/workspace/fonco/createProjectFromTerminal/node_modules/sync-prompt
45 verbose tar unpack /Users/daniel/.npm/sync-prompt/0.4.2/package.tgz
46 verbose tar unpacking to /Users/daniel/workspace/fonco/createProjectFromTerminal/node_modules/sync-prompt
47 silly gentlyRm /Users/daniel/workspace/fonco/createProjectFromTerminal/node_modules/sync-prompt is being purged
48 verbose gentlyRm don't care about contents; nuking /Users/daniel/workspace/fonco/createProjectFromTerminal/node_modules/sync-prompt
49 silly gunzTarPerm modes [ '755', '644' ]
50 silly gunzTarPerm extractEntry package.json
51 silly gunzTarPerm extractEntry .npmignore
52 silly gunzTarPerm extractEntry README.md
53 silly gunzTarPerm extractEntry LICENSE
54 silly gunzTarPerm extractEntry test.js
55 silly gunzTarPerm extractEntry HISTORY.md
56 silly gunzTarPerm extractEntry binding.gyp
57 silly gunzTarPerm extractEntry lib/sync-prompt.js
58 silly gunzTarPerm extractEntry src/sync_prompt.cc
59 info preinstall sync-prompt@0.4.2
60 silly install resolved []
61 verbose about to build /Users/daniel/workspace/fonco/createProjectFromTerminal/node_modules/sync-prompt
62 info build /Users/daniel/workspace/fonco/createProjectFromTerminal/node_modules/sync-prompt
63 verbose linkStuff [ false,
63 verbose linkStuff   false,
63 verbose linkStuff   false,
63 verbose linkStuff   '/Users/daniel/workspace/fonco/createProjectFromTerminal/node_modules' ]
64 info linkStuff sync-prompt@0.4.2
65 verbose linkBins sync-prompt@0.4.2
66 verbose linkMans sync-prompt@0.4.2
67 verbose rebuildBundles sync-prompt@0.4.2
68 info install sync-prompt@0.4.2
69 verbose unsafe-perm in lifecycle true
70 info sync-prompt@0.4.2 Failed to exec install script
71 verbose unlock done using /Users/daniel/.npm/_locks/sync-prompt-0f417bb4b3218d70.lock for /Users/daniel/workspace/fonco/createProjectFromTerminal/node_modules/sync-prompt
72 verbose stack Error: sync-prompt@0.4.2 install: `node-gyp rebuild`
72 verbose stack Exit status 1
72 verbose stack     at EventEmitter.<anonymous> (/Users/daniel/.nvm/v0.12.2/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
72 verbose stack     at EventEmitter.emit (events.js:110:17)
72 verbose stack     at ChildProcess.<anonymous> (/Users/daniel/.nvm/v0.12.2/lib/node_modules/npm/lib/utils/spawn.js:14:12)
72 verbose stack     at ChildProcess.emit (events.js:110:17)
72 verbose stack     at maybeClose (child_process.js:1015:16)
72 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
73 verbose pkgid sync-prompt@0.4.2
74 verbose cwd /Users/daniel/workspace/fonco/createProjectFromTerminal
75 error Darwin 14.3.0
76 error argv "/Users/daniel/.nvm/v0.12.2/bin/node" "/Users/daniel/.nvm/v0.12.2/bin/npm" "install" "sync-prompt"
77 error node v0.12.2
78 error npm  v2.7.4
79 error code ELIFECYCLE
80 error sync-prompt@0.4.2 install: `node-gyp rebuild`
80 error Exit status 1
81 error Failed at the sync-prompt@0.4.2 install script 'node-gyp rebuild'.
81 error This is most likely a problem with the sync-prompt package,
81 error not with npm itself.
81 error Tell the author that this fails on your system:
81 error     node-gyp rebuild
81 error You can get their info via:
81 error     npm owner ls sync-prompt
81 error There is likely additional logging output above.
82 verbose exit [ 1, true ]
83 verbose unbuild node_modules/sync-prompt
84 info preuninstall sync-prompt@0.4.2
85 info uninstall sync-prompt@0.4.2
86 verbose unbuild rmStuff sync-prompt@0.4.2 from /Users/daniel/workspace/fonco/createProjectFromTerminal/node_modules
87 info postuninstall sync-prompt@0.4.2
88 silly gentlyRm /Users/daniel/workspace/fonco/createProjectFromTerminal/node_modules/sync-prompt is being purged from base /Users/daniel/workspace/fonco/createProjectFromTerminal
89 verbose gentlyRm don't care about contents; nuking /Users/daniel/workspace/fonco/createProjectFromTerminal/node_modules/sync-prompt
90 silly vacuum-fs purging /Users/daniel/workspace/fonco/createProjectFromTerminal/node_modules/sync-prompt
91 silly vacuum-fs quitting because other entries in /Users/daniel/workspace/fonco/createProjectFromTerminal/node_modules
```

Best Regards

**Comment by JamesMGreene** [comment]
Also running into this.

I switched over to using the NPM module [readline-sync](https://www.npmjs.com/package/readline-sync) instead... definitely not as big a fan of the API (or the fact that it will downgrade to continually checking for file existence, which -- from past experience -- tends to burn up the CPU) but it suffices for my immediate needs.

**Comment by Qix-** [comment]
Another one for this.

**Comment by ghost** [comment]
It also fails on mac, that makes sense mac OS X is darwin based, any one got a fix for this?

**Comment by aaronfranco** [comment]
Fails on OSX using Node.js v[ 5.1.0, 4.2.3, 0.12.7, 0.12.2 ]  NPM v3.5.3

```
  CXX(target) Release/obj.target/sync_prompt/src/sync_prompt.o
../src/sync_prompt.cc:33:18: error: variable has incomplete type 'struct termios'
  struct termios tty;
                 ^
../src/sync_prompt.cc:33:10: note: forward declaration of 'termios'
  struct termios tty;
         ^
../src/sync_prompt.cc:36:21: error: use of undeclared identifier 'ECHO'
    tty.c_lflag &= ~ECHO;
                    ^
../src/sync_prompt.cc:38:20: error: use of undeclared identifier 'ECHO'
    tty.c_lflag |= ECHO;
                   ^
../src/sync_prompt.cc:40:34: error: use of undeclared identifier 'TCSANOW'
  (void) tcsetattr(STDIN_FILENO, TCSANOW, &tty);
```

It installs with Node.js v0.10.9
