### ISSUE TITLE
Throws in module.js:355

### ISSUE THREAD

**Issue by pjobson** [shovon/sync-prompt#18]
Script fails to run, I reduced my script to the following and it always throws.

    #!/usr/bin/env node
    var prompt = require('sync-prompt').prompt;    // https://github.com/shovon/sync-prompt

Error:

    module.js:355
      Module._extensions[extension](this, filename);
                                   ^
    Error: dlopen(/Users/jobsonp/mounts/mint_tools/node_modules/sync-prompt/build/Release/sync_prompt.node, 1): no suitable image found.  Did find:
        /Users/jobsonp/mounts/mint_tools/node_modules/sync-prompt/build/Release/sync_prompt.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x01 0x01 0x01 0x00
        at Error (native)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/Users/jobsonp/mounts/mint_tools/node_modules/sync-prompt/lib/sync-prompt.js:3:19)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)

**Comment by machawk1** [comment]
Same problem here. Reverting to Node v0.10.x will allow you to regain the functionality in the meantime. This occurs for me in both Node v0.12.x and the newly released v4.0.0.
