### ISSUE TITLE
npm failure

### ISSUE THREAD

**Issue by rightisleft** [shovon/sync-prompt#20]
I'm getting the following error when trying to install the package:

➜  ✗ npm install

> sync-prompt@0.4.2 install /Users/me/projects/thing/node_modules/sync-prompt
> node-gyp rebuild

  CXX(target) Release/obj.target/sync_prompt/src/sync_prompt.o
../src/sync_prompt.cc:33:18: error: variable has incomplete type 'struct termios'
  struct termios tty;
                 ^
../src/sync_prompt.cc:33:10: note: forward declaration of 'termios'
  struct termios tty;
         ^
../src/sync_prompt.cc:36:21: error: use of undeclared identifier 'ECHO'
    tty.c_lflag &= ~ECHO;
                    ^
../src/sync_prompt.cc:38:20: error: use of undeclared identifier 'ECHO'
    tty.c_lflag |= ECHO;
                   ^
../src/sync_prompt.cc:40:34: error: use of undeclared identifier 'TCSANOW'
  (void) tcsetattr(STDIN_FILENO, TCSANOW, &tty);
                                 ^
4 errors generated.
make: **\* [Release/obj.target/sync_prompt/src/sync_prompt.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jmurphy/projects/thing/node_modules/sync-prompt
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN thing@1.0.0 No repository field.
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! sync-prompt@0.4.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sync-prompt@0.4.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sync-prompt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sync-prompt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sync-prompt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by vihanb** [comment]
Having this same problem. Perhaps this some incompatibility in the bindings?

**Comment by psalvitti** [comment]
Same problem here ... MacOS (El Capitan). node up-to-date, npm up-to-date, all dependencies up-to-date:

![image](https://cloud.githubusercontent.com/assets/828456/16540754/17893812-403d-11e6-9bee-378fc4093268.png)

**Comment by john-chei** [comment]
Same here =/

**Comment by alejandroereyes** [comment]
Having the same issue, here's the stack.

```

> sync-prompt@0.4.2 install /node_modules/sync-prompt
> node-gyp rebuild

  CXX(target) Release/obj.target/sync_prompt/src/sync_prompt.o
../src/sync_prompt.cc:33:18: error: variable has incomplete type 'struct termios'
  struct termios tty;
                 ^
../src/sync_prompt.cc:33:10: note: forward declaration of 'termios'
  struct termios tty;
         ^
../src/sync_prompt.cc:36:21: error: use of undeclared identifier 'ECHO'
    tty.c_lflag &= ~ECHO;
                    ^
../src/sync_prompt.cc:38:20: error: use of undeclared identifier 'ECHO'
    tty.c_lflag |= ECHO;
                   ^
../src/sync_prompt.cc:40:34: error: use of undeclared identifier 'TCSANOW'
  (void) tcsetattr(STDIN_FILENO, TCSANOW, &tty);
                                 ^
4 errors generated.
make: *** [Release/obj.target/sync_prompt/src/sync_prompt.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/Cellar/node/5.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/sync-prompt
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/5.1.0/bin/node" "/usr/local/bin/npm" "install" "sync-prompt"
npm ERR! node v5.1.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! sync-prompt@0.4.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sync-prompt@0.4.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sync-prompt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sync-prompt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sync-prompt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

**Comment by ghost** [comment]
Same issue here, Ubuntu 16.10 with latest updates.

**Comment by vihanb** [comment]
Since this isn't working with node anymore and the author doesn't seem to be supporting it. I've created an alternative version [syncprompt](https://github.com/cheddar-lang/syncprompt) which very closely replicates this module's behavior but successfully builds.
