### ISSUE TITLE
not install

### ISSUE THREAD

**Issue by splincode** [shovon/sync-prompt#21]
`
splincode@splincode-MS-7996:~/Downloads/test$ sudo npm install sync-prompt
[sudo] пароль для splincode:         

> sync-prompt@0.4.2 install /home/splincode/Downloads/test/node_modules/sync-prompt
> node-gyp rebuild

make: вход в каталог «/home/splincode/Downloads/test/node_modules/sync-prompt/build»
  CXX(target) Release/obj.target/sync_prompt/src/sync_prompt.o
../src/sync_prompt.cc: In function ‘void setStdinEcho(bool)’:
../src/sync_prompt.cc:33:18: error: aggregate ‘setStdinEcho(bool)::termios tty’ has incomplete type and cannot be defined
   struct termios tty;
                  ^
../src/sync_prompt.cc:34:31: error: ‘tcgetattr’ was not declared in this scope
   tcgetattr(STDIN_FILENO, &tty);
                               ^
../src/sync_prompt.cc:36:21: error: ‘ECHO’ was not declared in this scope
     tty.c_lflag &= ~ECHO;
                     ^
../src/sync_prompt.cc:38:20: error: ‘ECHO’ was not declared in this scope
     tty.c_lflag |= ECHO;
                    ^
../src/sync_prompt.cc:40:34: error: ‘TCSANOW’ was not declared in this scope
   (void) tcsetattr(STDIN_FILENO, TCSANOW, &tty);
                                  ^
../src/sync_prompt.cc:40:47: error: ‘tcsetattr’ was not declared in this scope
   (void) tcsetattr(STDIN_FILENO, TCSANOW, &tty);
                                               ^
sync_prompt.target.mk:92: ошибка выполнения рецепта для цели «Release/obj.target/sync_prompt/src/sync_prompt.o»
make: *** [Release/obj.target/sync_prompt/src/sync_prompt.o] Ошибка 1
make: выход из каталога «/home/splincode/Downloads/test/node_modules/sync-prompt/build»
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-78-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/splincode/Downloads/test/node_modules/sync-prompt
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
npm WARN blackbox-stress-test@1.0.0 No repository field.
npm ERR! Linux 4.4.0-78-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "sync-prompt"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! sync-prompt@0.4.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sync-prompt@0.4.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sync-prompt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sync-prompt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sync-prompt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/splincode/.npm/_logs/2017-06-06T10_43_58_587Z-debug.log

`

**Comment by wwwflorencio** [comment]
I get the same error on ubuntu :/
